version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tacl
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.Version={{.Version}}"

archives:
  # Archive containing only the `tacl` binary
  - id: tacl-archive
    format: tar.gz
    builds:
      - tacl
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
